language: perl
perl:
  - "5.22"

before_install:
  - mkdir ~/.dzil/
  - echo '[%Rights]' >> ~/.dzil/config.ini
  - echo 'license_class    = Perl_5' >> ~/.dzil/config.ini
  - echo 'copyright_holder = Leo Lapworth' >> ~/.dzil/config.ini

install:
   - cpanm --quiet --notest --skip-satisfied Dist::Zilla
   - cpanm Test::NoTabs
   - "dzil authordeps | grep -vP '[^\\w:]' | cpanm --verbose --notest --skip-satisfied"
   - "dzil listdeps   | grep -vP '[^\\w:]' | cpanm --verbose --skip-satisfied"

script:
  - dzil smoke --release --author

notifications:
  email:
    recipients:
      - llap@cpan.org
    on_success: always
    on_failure: always

